### ISSUE TITLE
Rewrite from scratch without decompiling existing copyrighted code.

### ISSUE THREAD

**Issue by touil** [vgpastor/SDR-Tetra-Plugin#1]
As in the title.

**Comment by vgpastor** [comment]
The original library are open source and the original code it's possible to see in the branch https://github.com/vgpastor/SDR-Tetra-Plugin/tree/OriginalCode

**Comment by vgpastor** [comment]
I updated the documentation to add this comment, https://github.com/vgpastor/SDR-Tetra-Plugin/wiki

If you or any other develop works in the original project, please tell me to add to credits, i only try to learn more about tetra.
